# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'group_detail',
            },
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('count', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group_info',
            },
        ),
        migrations.CreateModel(
            name='Per',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'per',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='per',
            name='roles',
            field=models.ManyToManyField(to='shop.Role'),
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.GroupInfo'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='shop.User'),
        ),
    ]
